//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparisProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Gor
    {
        public Nullable<int> IsletmeNo { get; set; }
        public Nullable<double> MenuFiyat { get; set; }
        public string MenuAd { get; set; }
        public int MenuNo { get; set; }
        public int IcecekNo { get; set; }
        public string IcecekAd { get; set; }
        public Nullable<double> IcecekFiyat { get; set; }
        public int YiyecekNo { get; set; }
        public string YiyecekAd { get; set; }
        public Nullable<double> YiyecekFiyat { get; set; }
    }
}
