//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparisProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int MenuNo { get; set; }
        public Nullable<int> IsletmeNo { get; set; }
        public Nullable<int> IcecekNo { get; set; }
        public Nullable<int> YiyecekNo { get; set; }
        public string MenuAd { get; set; }
        public Nullable<double> MenuFiyat { get; set; }
    
        public virtual Icecek Icecek { get; set; }
        public virtual Isletme Isletme { get; set; }
        public virtual Yiyecek Yiyecek { get; set; }
    }
}
