//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparisProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Roles
    {
        public int KullaniciNo { get; set; }
        public string KullaniciAd { get; set; }
        public string MailAdress { get; set; }
        public Nullable<int> KullaniciTipNo { get; set; }
        public string KullaniciTipiAd { get; set; }
    }
}
